apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  labels:
    app.kubernetes.io/name: {{ include "ydirect-vbai.name" . }}
    helm.sh/chart: {{ include "ydirect-vbai.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- toYaml .Values.configMap.data | nindent 2 }} 